# Generated by Django 2.2.4 on 2019-12-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='U.S.A.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
