# Generated by Django 2.2.4 on 2019-12-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='requirements',
            field=models.TextField(default='empty'),
        ),
    ]
