# Generated by Django 2.2.4 on 2019-12-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_scholar_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='scholarship_link',
            field=models.URLField(default='empty'),
        ),
    ]
