# Generated by Django 2.2.4 on 2019-12-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0003_auto_20191203_0243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholar',
            options={'ordering': ['award_amount']},
        ),
        migrations.AlterField(
            model_name='scholar',
            name='award_amount',
            field=models.IntegerField(default=0),
        ),
    ]
