# Generated by Django 2.2.4 on 2019-12-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0005_auto_20191203_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholar',
            options={'ordering': ['id']},
        ),
    ]
