# Generated by Django 2.2.8 on 2019-12-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.TextField(blank=True, default='empty', null=True)),
                ('scholarship_link', models.TextField(blank=True, default='empty', null=True)),
                ('award_amount', models.TextField(blank=True, default='empty', null=True)),
                ('geographic_requisite', models.TextField(blank=True, default='empty', null=True)),
                ('enrollment_requisite', models.TextField(blank=True, default='empty', null=True)),
                ('major_requisite', models.TextField(blank=True, default='empty', null=True)),
                ('description', models.TextField(blank=True, default='empty', null=True)),
                ('requirements', models.TextField(blank=True, default='empty', null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
