# Generated by Django 2.2.4 on 2019-12-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_auto_20191203_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='award_amount',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='enrollment_requisite',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='geographic_requisite',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='major_requisite',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='scholarship_link',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='scholarship_name',
            field=models.TextField(default='empty'),
        ),
    ]
