# Generated by Django 2.2.4 on 2019-12-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_auto_20191203_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.TextField(default='empty')),
                ('scholarship_link', models.TextField(default='empty')),
                ('award_amount', models.TextField(default='empty')),
                ('geographic_requisite', models.TextField(default='empty')),
                ('enrollment_requisite', models.TextField(default='empty')),
                ('major_requisite', models.TextField(default='empty')),
                ('description', models.TextField(default='empty')),
            ],
        ),
    ]
