# Generated by Django 2.2.4 on 2019-12-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_scholar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='award_amount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='enrollment_requisite',
        ),
        migrations.RemoveField(
            model_name='post',
            name='geographic_requisite',
        ),
        migrations.RemoveField(
            model_name='post',
            name='major_requisite',
        ),
        migrations.RemoveField(
            model_name='post',
            name='scholarship_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='scholarship_name',
        ),
    ]
