# Generated by Django 2.2.4 on 2019-12-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_auto_20191203_0125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholar',
        ),
    ]
